"""mis a jour des attribut commande

Revision ID: 00af728f9c3f
Revises: 
Create Date: 2025-04-01 15:41:05.578090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00af728f9c3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commande',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('panier_id', sa.Integer(), nullable=True),
    sa.Column('nom_produit', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('prix_produit', sa.Integer(), nullable=False),
    sa.Column('prix_total_commande', sa.Float(), nullable=False),
    sa.Column('quantite_panier', sa.Integer(), nullable=False),
    sa.Column('quantite_commande', sa.Integer(), nullable=False),
    sa.Column('date_commande', sa.DateTime(), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('prix', sa.Float(), nullable=False),
    sa.Column('quantite_disponible', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('panier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('prix_total', sa.Float(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['produit_id'], ['produit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('panier')
    op.drop_table('produit')
    op.drop_table('commande')
    # ### end Alembic commands ###
